### PR TITLE
Update citation formats we support.

### PR DESCRIPTION
**Pull request by adlius**
Ticket: https://openscience.atlassian.net/browse/OSF-8515

## QA Notes:

It is worth to do another pass over all the citation formats to see what's not working since we add 400+ more citation formats in this PR.

### CODE REVIEW

**Comment by brianjgeiger** [comment]
@adlius Have you tested with the OSF to see what the consequences of using this are? We override a couple of things; do those still work and/or are the overrides necessary? We have some ways of testing the citation formats, do those tests still pass appropriately?

**Comment by adlius** [comment]
@brianjgeiger According to what I know about the citation formats, this should not break OSF. But yes I should go and test this out in case some XML file could not be parsed or parsed incorrectly by our parsing script.
As for the overrides, I only know about the three Bluebook exceptions, which would not be impacted by this PR. But I will also test it out.

**Comment by adlius** [comment]
Briefly tested and confirmed it does not break citation widgets on OSF. Added QA notes.

**Comment by brianjgeiger** [comment]
@sloria Can you merge this, please?

**Comment by sloria** [comment]
@brianjgeiger Before merging, we'll need to pin to a commit or version on OSF: https://github.com/CenterForOpenScience/osf.io/blob/d157dfbd921c391b63af0db3904a6ca0590fd57b/bower.json#L16 . Can you or someone on your team do that?

**Comment by brianjgeiger** [comment]
Done

**Pull request merged**
